title: 'Kitakyushu JALT'
default_lang: en
author:
  name: 'Website Administrator'
  email: kitakyushu@jalt.org
taxonomies:
  - content
  - events
  - year
metadata:
  description: 'This is the website for the Japan Association for Language Teaching Kitakyushu chapter'
summary:
  enabled: true
  format: short
  size: 60
  delimiter: '==='
redirects:
  /schedule/([^/]+)/([^/]+)/([^/]+)$: /schedule/archive/$1-$2-$3[301]
routes: null
blog:
  route: /blog
